CREATE TABLE dbo.status (
id INT IDENTITY(1,1) NOT NULL,
name VARCHAR(100) NOT NULL,
CONSTRAINT PK_status PRIMARY KEY CLUSTERED (id ASC)
) ON [PRIMARY];

CREATE TABLE dbo.posts (
id INT IDENTITY(1,1) NOT NULL,
name VARCHAR(100) NOT NULL,
CONSTRAINT PK_posts PRIMARY KEY CLUSTERED (id ASC)
) ON [PRIMARY];

CREATE TABLE dbo.deps (
id INT IDENTITY(1,1) NOT NULL,
name VARCHAR(100) NOT NULL,
CONSTRAINT PK_deps PRIMARY KEY CLUSTERED (id ASC)
) ON [PRIMARY];

CREATE TABLE dbo.persons (
id INT IDENTITY(1,1) NOT NULL,
first_name VARCHAR(100) NOT NULL,
second_name VARCHAR(100) NOT NULL,
last_name VARCHAR(100) NOT NULL,
date_employ DATETIME NULL,
date_uneploy DATETIME NULL,
status_id INT NOT NULL,
dep_id INT NOT NULL,
post_id INT NOT NULL,
CONSTRAINT PK_persons PRIMARY KEY CLUSTERED (id ASC),
CONSTRAINT FK_persons_status FOREIGN KEY (status_id) REFERENCES dbo.status(id),
CONSTRAINT FK_persons_deps FOREIGN KEY (dep_id) REFERENCES dbo.deps(id),
CONSTRAINT FK_persons_posts FOREIGN KEY (post_id) REFERENCES dbo.posts(id)
) ON [PRIMARY];